#!/bin/sh
# $Id$
# $Name$

builddir=`pwd`
if [ -z "$srcdir" ]
then
  srcdir=.
fi

test_program=updatetest
test_libs=$builddir/../gedcom/libgedcom.la

. $srcdir/src/test_prologue.sh
. $srcdir/src/test_bulk.sh
