#!/bin/sh
# $Id$
# $Name$

builddir=`pwd`
if [ -z "$srcdir" ]
then
  srcdir=.
fi

. $srcdir/src/test_prologue.sh

file=$1

if [ -z "$srcdir" ]
then
  testfile=$file
else
  case $file in
    ./*) testfile=$file ;;
    *)   testfile=$srcdir/input/$file ;;
  esac
fi

test_program=testgedcom
test_libs=$builddir/../gedcom/libgedcom.la
test_args=$testfile

. $srcdir/src/test_bulk.sh
