#!/bin/sh
# $Id$
# $Name$

options="-q"
extra_options=

while [ $# -gt 0 ]
do
  case "$1" in
    -*) extra_options="$extra_options $1";;
    *)  break;;
  esac
  shift
done

expected_result=$1
if [ -z "$expected_result" ]
then
  expected_result=0
fi

# For use outside Makefile
if [ -z "$srcdir" ]
then
  srcdir=.
  options=$extra_options
else
  options="$options $extra_options"
fi

builddir=`pwd`
ltcmd="$builddir/../libtool --mode=execute -dlopen $builddir/../gedcom/libgedcom.la"
export GCONV_PATH=.:$GCONV_PATH
ln -s $srcdir/../data/gedcom.enc .
ln -s $srcdir/../data/new.ged .
ln -s $builddir/../iconv/glibc/.libs/ANSI_Z39.47.so .
ln -s $srcdir/../iconv/glibc/gconv-modules .
rm -f core
$ltcmd $GEDCOM_TESTENV $builddir/src/updatetest $options
result=$?
rm gedcom.enc
rm new.ged
rm ANSI_Z39.47.so
rm gconv-modules
if [ "$result" -eq "$expected_result" -a ! -r core ]
then
  exit 0
else
  exit 1
fi
