#!/usr/bin/env perl

use strict;
use diagnostics;

my ($inputfile, $outputfile) = @ARGV;

my %tags;

open INPUT, $inputfile or die "Can't read $inputfile\n";
open OUTPUT, ">$outputfile" or die "Can't write $outputfile\n";
    
while (<INPUT>)
{
  if (/((?:USER)?TAG(?:_\w+)?).+?(\d+)/) {
    my ($name, $num) = ($1, $2);
    $tags{$num} = $name;
  }
}

print OUTPUT "/* External header for the Gedcom parser library.\n";
print OUTPUT "   Copyright (C) 2001,2002 The Genes Development Team\n";
print OUTPUT "   This file is part of the Gedcom parser library.\n";
print OUTPUT "   Contributed by Peter Verthez <Peter.Verthez\@advalvas.be>, 2001.\n";
print OUTPUT "\n";
print OUTPUT "   The Gedcom parser library is free software; you can redistribute it\n";
print OUTPUT "   and/or modify it under the terms of the GNU Lesser General Public\n";
print OUTPUT "   License as published by the Free Software Foundation; either\n";
print OUTPUT "   version 2.1 of the License, or (at your option) any later version.\n";
print OUTPUT "\n";
print OUTPUT "   The Gedcom parser library is distributed in the hope that it will be\n";
print OUTPUT "   useful, but WITHOUT ANY WARRANTY; without even the implied warranty of\n";
print OUTPUT "   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n";
print OUTPUT "   Lesser General Public License for more details.\n";
print OUTPUT "\n";
print OUTPUT "   You should have received a copy of the GNU Lesser General Public\n";
print OUTPUT "   License along with the Gedcom parser library; if not, write to the\n";
print OUTPUT "   Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA\n";
print OUTPUT "   02111-1307 USA.  */\n";
print OUTPUT "\n";
print OUTPUT "#ifndef GEDCOM_TAGS_H\n";
print OUTPUT "#define GEDCOM_TAGS_H\n";
print OUTPUT "\n";
print OUTPUT "/* This file is automatically generated */\n";
print OUTPUT "\n";

foreach my $tagnum (sort keys %tags) {
  print OUTPUT "#define $tags{$tagnum}\t$tagnum\n";
}

print OUTPUT "\n";
print OUTPUT "#endif\n";

close OUTPUT;
close INPUT;

