#!/bin/sh
# $Id$
# $Name$

options="-q"
extra_options=
dmalloc=`which dmalloc`

while [ $# -gt 0 ]
do
  case "$1" in
    -*) extra_options="$extra_options $1";;
    *)  break;;
  esac
  shift
done

file=$1
expected_result=$2
if [ -z "$expected_result" ]
then
  expected_result=0
fi

# For use outside Makefile
if [ -z "$srcdir" ]
then
  testfile=$file
  srcdir=.
  options=$extra_options
else
  testfile=input/$file
  options="$options $extra_options"
fi

builddir=`pwd`
export GCONV_PATH=../ansel:$GCONV_PATH
export LD_LIBRARY_PATH=$builddir/../gedcom/.libs:$builddir/../gom/.libs:$LD_LIBRARY_PATH
cp $builddir/../ansel/.libs/ANSI_Z39.47.so ../ansel
rm -f core
if [ "$GOM_DMALLOC_TEST" = "" ]
then
  $builddir/gomtest $options $testfile
else
  $dmalloc -b -l dmalloc.log -i 100 low > dmalloc.env
  . dmalloc.env
  rm dmalloc.env
  $builddir/gomtest_static $options $testfile
fi
result=$?
rm ../ansel/ANSI_Z39.47.so
if [ "$result" -eq "$expected_result" -a ! -r core ]
then
  exit 0
else
  exit 1
fi
