#!/bin/sh
# $Id$
# $Name$

options="-q"

while [ $# -gt 0 ]
do
  case "$1" in
    -*) options="$options $1";;
    *)  break;;
  esac
  shift
done

file=$1
expected_result=$2
if [ -z "$expected_result" ]
then
  expected_result=0
fi

builddir=`pwd`
cd $srcdir/..
export GCONV_PATH=./ansel:$GCONV_PATH
export LD_LIBRARY_PATH=$builddir/../gedcom/.libs:$LD_LIBRARY_PATH
cp $builddir/../ansel/.libs/ANSI_Z39.47.so ansel
$builddir/../testgedcom $options t/input/$file
result=$?
rm ansel/ANSI_Z39.47.so
if [ "$result" -eq "$expected_result" ]
then
  exit 0
else
  exit 1
fi
